apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: on-demand
spec:
  disruption:
    budgets:
    - nodes: 50%
    - duration: 14h
      nodes: "1"
      schedule: 0 8 * * *
    consolidateAfter: 2m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 20
    memory: 40Gi
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: capacity-spread
        operator: In
        values:
        - "1"
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3
        - t3a
        - m5
        - c5
        - c5n
      - key: topology.kubernetes.io/zone
        operator: In
        values:
          - sa-east-1a
          - sa-east-1b
          - sa-east-1c
      terminationGracePeriod: 5m