apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-24T16:09:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4135097"
  uid: 1aa9737a-2eb0-4519-a545-f710b9b1b011
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::908671954593:role/FargatePodExecutionRole-arch-eks-01-02
      username: system:node:{{SessionName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::908671954593:role/KarpenterNodeRole-arch-eks-01-02
      username: system:node:{{EC2PrivateDNSName}}