# Default NodeClass to provisione EC2 Nodes Bottlerocket #
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket
  annotations:
    helm.sh/hook: post-install
spec:
  kubelet:
    maxPods: 20
    systemReserved:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: 1Gi
    evictionHard:
        memory.available: 5%
        nodefs.available: 10%
        nodefs.inodesFree: 10%
    imageGCHighThresholdPercent: 85
    imageGCLowThresholdPercent: 80
    cpuCFSQuota: true
  amiSelectorTerms:
      - id: ami-04ba2191c69d4b603 #sp
      - id: ami-05bf4b522f9d46749 #ohio
  amiFamily: Bottlerocket
  instanceProfile: KarpenterNodeInstanceProfile-munin-eks-hml # this IAM Role needs be set in aws-auth configmap.
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "true"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/security-group: arch-eks-01-02
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required        
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
    # Data device: Container resources such as images and logs
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  tags:
    cluster: arch-eks-01-02
    service: go-ledger
    squad: architecture
  userData: |
    [settings.bootstrap-containers.cis-bootstrap]
    "source" = "111066175892.dkr.ecr.us-east-2.amazonaws.com/bottlerocket-cis-karpenter:bootstrap"
    "mode" = "always"
    "essential" = true
    [settings.kernel.sysctl]
    # 3.1.1
    "net.ipv4.conf.all.send_redirects" = "0"
    "net.ipv4.conf.default.send_redirects" = "0"
    # 3.2.2
    "net.ipv4.conf.all.accept_redirects" = "0"
    "net.ipv4.conf.default.accept_redirects" = "0"
    "net.ipv6.conf.all.accept_redirects" = "0"
    "net.ipv6.conf.default.accept_redirects" = "0"
    # 3.2.3
    "net.ipv4.conf.all.secure_redirects" = "0"
    "net.ipv4.conf.default.secure_redirects" = "0"
    # 3.2.4
    "net.ipv4.conf.all.log_martians" = "1"
    "net.ipv4.conf.default.log_martians" = "1"